Information:
  Title: "emma's blog"
  Icon: emma.png
  Description: "I'm Emma, a self-taught developer who primarily sells and contributes to software on the interwebs."
  Link: prpl.wtf
  Theme: CatppuccinMocha

Connections:
  GitHub: prplwtf
  YouTube:
  Bluesky: prpl.wtf
  Twitter:
  Mastodon: ivy@quack.social
