Information:
  Title: emma
  Icon: emma.png
  Description: I'm Emma, a self-taught developer who primarily sells and contributes to software on the interwebs.
  Link: prpl.wtf
  Theme: Default

Connections:
  GitHub: prplwtf
  YouTube:
  Twitter: prplwtf
  Mastodon: ivy@quack.social